version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - echo "AWS CLI version:"
      - aws --version
      - echo "No third-party packages needed - using pure bash!"

  pre_build:
    commands:
      - echo "Validating credentials..."
      - aws sts get-caller-identity
      - echo "Loading deployment plan..."
      - ls -la
      - echo "=== Plan contents ==="
      - cat plan.txt
      - echo "=== End plan ==="

  build:
    commands:
      - echo "Executing deployment..."
      - chmod +x ./deploy.sh
      - ./deploy.sh

  post_build:
    commands:
      - echo "Deployment complete!"
      - echo "Check your email for summary notification."